### ISSUE TITLE
Option to run it as web service

### ISSUE THREAD

**Issue by kakumanivrn** [jsetton/alexa-assistant#15]
It would be great if you can help me set this up as web service since my AWS and Alexa dev accounts are different and I can't create new AWS account with same email ID. Also it's easier to host and manage it on different clouds than AWS.

**Comment by jsetton** [comment]
The focus for the deployment method I implemented is with ASK-CLI which solely uses AWS as backend cloud service. You are free to use the source code on my repository for how you want to setup the skill on your end.

On a side note, AWS and Alexa accounts are technically different from Amazon perspective since these are two distinct services.
